### ISSUE TITLE
assert_that optimisation?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [Leszek-Sieminski/RAhrefs#2]
Really useful library thanks, I was just looking through it and saw this: https://github.com/Leszek-Sieminski/RAhrefs/blob/7132390b10c804c9ac2917c2a58b44a37609da5f/R/downloader.R#L113-L138

...which I think won't perform as you intend.  The `assertthat` conditions need to be within `assert_that()` to trigger errors, so `assertthat::is.string(target)` just returns `TRUE` or `FALSE` rather than an error.  Also could list several in one condition.  

Also to save writing out `assertthat::` all the time, you can use `#' @import assertthat`  in the boilerplate.

As a suggestion:

```r

#' @import assertthat

..snip..

assert_that(!is.null(target),
                   !is.na(target),
                    is.string(target),  # this will trigger an error now, doesn't as is
                    is.string(report),
                    !is.null(report),
                    etc...
) 
```

**Comment by Leszek-Sieminski** [comment]
Thanks, @MarkEdmondson1234, you were right - I fixed this part of the code :) Closing the issue.
